require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/Documentation:
  Enabled: False

Rails/DynamicFindBy:
  Enabled: False

Rails/RenderInline:
  Enabled: False

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**

RSpec/RepeatedExample:
  Exclude:
    - spec/policies/**

RSpec/VerifiedDoubles:
  Enabled: False

Metrics/MethodLength:
  Exclude:
    - db/migrate/**

Metrics/AbcSize:
  Exclude:
    - db/migrate/**
